name = "TravelingSalesmanGUI"
uuid = "569cb50a-c034-4b2b-9494-92919b2858e0"
authors = ["povolji2", "svadlmat"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1.8.1"
